#!/usr/bin/env python3
"""Generates assets/cones.svg, the README header: the scene, the pixel wordmark and the tagline. Run: python3 assets/cones.py"""

# 7x9 glyphs, two-pixel strokes, chamfered corners. Rendered as shaded cells, the way half-block terminal art reads.
GLYPHS = {
    "C": [".#####.", "##...##", "##.....", "##.....", "##.....", "##.....", "##.....", "##...##", ".#####."],
    "O": [".#####.", "##...##", "##...##", "##...##", "##...##", "##...##", "##...##", "##...##", ".#####."],
    "N": ["##...##", "###..##", "###..##", "##.#.##", "##.#.##", "##.#.##", "##..###", "##..###", "##...##"],
    "E": ["#######", "##.....", "##.....", "##.....", "######.", "##.....", "##.....", "##.....", "#######"],
    "S": [".######", "##...##", "##.....", "##.....", ".#####.", ".....##", ".....##", "##...##", "######."],
}
WORD, PX, PITCH, GAP_CELLS, X0, Y0 = "cones", 5.1, 5.6, 2, 250, 40
TAGLINE = "Traffic control for coding agents."

cells = []
x = 0
for ch in WORD:
    for r, row in enumerate(GLYPHS[ch.upper()]):
        cells += [(x + c, r) for c, bit in enumerate(row) if bit == "#"]
    x += 7 + GAP_CELLS
cols = x - GAP_CELLS
rows = len(next(iter(GLYPHS.values())))
W = int(X0 + max(cols * PITCH, len(TAGLINE) * 7.9) + 30)  # 13px monospace is about 7.9px per glyph

def rects(dx, dy, fill):
    return "\n".join(f'    <rect x="{X0 + c * PITCH + dx:.1f}" y="{Y0 + r * PITCH + dy:.1f}" width="{PX}" height="{PX}" rx=".7" fill="{fill}"/>'
                     for c, r in cells)

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="140" viewBox="0 0 {W} 140" role="img" aria-label="cones: {TAGLINE}">
  <!-- generated by assets/cones.py: a coding agent pulls up to the cones and waits its turn -->
  <defs>
    <clipPath id="cone-clip"><path d="M0 -80 L30 0 L-30 0 Z"/></clipPath>
    <g id="cone">
      <ellipse cx="0" cy="1" rx="40" ry="6" fill="#f97316" opacity=".3"/>
      <path d="M0 -80 L30 0 L-30 0 Z" fill="#f97316"/>
      <g clip-path="url(#cone-clip)" fill="#fff" opacity=".9">
        <rect x="-30" y="-54" width="60" height="12"/>
        <rect x="-30" y="-30" width="60" height="12"/>
      </g>
      <rect x="-36" y="-4" width="72" height="8" rx="3" fill="#f97316"/>
    </g>
    <linearGradient id="ink" gradientUnits="userSpaceOnUse" x1="0" y1="{Y0}" x2="0" y2="{Y0 + rows * PITCH}">
      <stop offset="0" stop-color="#fdba74"/>
      <stop offset=".45" stop-color="#f97316"/>
      <stop offset="1" stop-color="#c2410c"/>
    </linearGradient>
  </defs>

  <!-- road: rolls in with the car, then stops -->
  <line x1="0" y1="112" x2="240" y2="112" stroke="#9ca3af" stroke-width="2" opacity=".6"/>
  <line x1="0" y1="124" x2="240" y2="124" stroke="#9ca3af" stroke-width="3" stroke-dasharray="14 10" opacity=".7">
    <animate attributeName="stroke-dashoffset" values="0;-96" dur="1.4s" calcMode="spline" keySplines=".2 .8 .2 1" fill="freeze"/>
  </line>

  <!-- the agent -->
  <g>
    <animateTransform attributeName="transform" type="translate" values="-90 0;0 0" dur="1.4s" calcMode="spline" keySplines=".2 .8 .2 1" fill="freeze"/>
    <circle cx="22" cy="106" r="6" fill="#64748b"/>
    <circle cx="46" cy="106" r="6" fill="#64748b"/>
    <rect x="10" y="78" width="48" height="26" rx="7" fill="#3b82f6"/>
    <rect x="16" y="83" width="36" height="16" rx="3" fill="#0f172a"/>
    <text x="21" y="95" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace" font-size="11" font-weight="700" fill="#e2e8f0">&gt;<tspan><animate attributeName="opacity" values="1;1;0;0" dur="1s" repeatCount="indefinite"/>_</tspan></text>
    <!-- "on it, waiting" -->
    <g opacity="0">
      <animate attributeName="opacity" values="0;1" begin="1.4s" dur=".3s" fill="freeze"/>
      <path d="M46 72 L52 78 L56 72 Z" fill="#e5e7eb"/>
      <rect x="40" y="56" width="38" height="18" rx="9" fill="#e5e7eb"/>
      <circle cx="51" cy="65" r="2.4" fill="#6b7280"><animate attributeName="opacity" values="1;.2;1" dur="1.2s" repeatCount="indefinite"/></circle>
      <circle cx="59" cy="65" r="2.4" fill="#6b7280"><animate attributeName="opacity" values="1;.2;1" dur="1.2s" begin=".2s" repeatCount="indefinite"/></circle>
      <circle cx="67" cy="65" r="2.4" fill="#6b7280"><animate attributeName="opacity" values="1;.2;1" dur="1.2s" begin=".4s" repeatCount="indefinite"/></circle>
    </g>
  </g>

  <!-- the cones, receding -->
  <use href="#cone" transform="translate(126 112)"/>
  <use href="#cone" transform="translate(184 112) scale(.72)"/>
  <use href="#cone" transform="translate(224 112) scale(.5)"/>
  <!-- beacon on the lead cone -->
  <circle cx="126" cy="28" r="10" fill="#fde047" opacity=".35"><animate attributeName="opacity" values=".35;0;.35" dur="1s" repeatCount="indefinite"/></circle>
  <circle cx="126" cy="28" r="4.5" fill="#fde047"><animate attributeName="opacity" values="1;.25;1" dur="1s" repeatCount="indefinite"/></circle>

  <!-- wordmark: {cols}x{rows} cells, shadow then shaded ink -->
  <g opacity=".35">
{rects(2.2, 2.4, "#7c2d12")}
  </g>
  <g>
{rects(0, 0, "url(#ink)")}
  </g>
  <text x="{X0}" y="{Y0 + rows * PITCH + 24}" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace" font-size="13" fill="#9ca3af">{TAGLINE}</text>
</svg>
'''
open("assets/cones.svg", "w").write(svg)
print(f"assets/cones.svg: {W}x140, {len(cells)} cells")
