#!/usr/bin/env python3
"""Generate the README header: two pixel cars queue beside Little feet."""
from pathlib import Path

ASSETS = Path(__file__).resolve().parent
TAGLINE = "Traffic control for agents."
W, H = 572, 140
WORD, PX, PITCH, GAP_CELLS, X0, Y0 = "cones", 5.1, 5.6, 2, 250, 40
GLYPHS = {
    "C": [".#####.", "##...##", "##.....", "##.....", "##.....", "##.....", "##.....", "##...##", ".#####."],
    "O": [".#####.", "##...##", "##...##", "##...##", "##...##", "##...##", "##...##", "##...##", ".#####."],
    "N": ["##...##", "###..##", "###..##", "##.#.##", "##.#.##", "##.#.##", "##..###", "##..###", "##...##"],
    "E": ["#######", "##.....", "##.....", "##.....", "######.", "##.....", "##.....", "##.....", "#######"],
    "S": [".######", "##...##", "##.....", "##.....", ".#####.", ".....##", ".....##", "##...##", "######."],
}
LITTLE_FEET = (ASSETS / "little-feet.txt").read_text().splitlines()
CAR = [
    "..bbbbbbbbbbbb..",
    ".bbbbbbbbbbbbbb.",
    "bbbnnnnnnnnnnbbb",
    "bbbnnnnnnnnnnbbb",
    "bbbnnnnnnnnnnbbb",
    "bbbnnnnnnnnnnbbb",
    ".bbbbbbbbbbbbbb.",
    "..bbbbbbbbbbbb..",
    "...ddd....ddd...",
    "...ddd....ddd...",
]
COLORS = {"o": "#ff8700", "w": "#f1eadf", "b": "#3b82f6", "n": "#0f172a", "d": "#64748b"}


def pixels(sprite):
    return "".join(
        f'<rect x="{col}" y="{row}" width="1" height="1" fill="{COLORS[pixel]}"/>'
        for row, line in enumerate(sprite)
        for col, pixel in enumerate(line)
        if pixel != "."
    )


def little_feet(cx, pixel, blink=False):
    art = f'''<g transform="translate({cx - 3.5 * pixel} {112 - 6 * pixel}) scale({pixel})">
      <ellipse cx="3.5" cy="6.04" rx="3.5" ry=".2" fill="#ff8700" opacity=".17"/>
      {pixels(LITTLE_FEET)}
      <path d="M2 3h1v1H2z M4 3h1v1H4z" fill="#0d1117"/>'''
    if blink:
        art += '''<path d="M2 3h1v1H2z M4 3h1v1H4z" fill="#ff8700" opacity="0">
          <animate attributeName="opacity" values="0;0;1;0;0" keyTimes="0;.70;.715;.75;1" dur="5s" repeatCount="indefinite"/>
        </path>'''
    return art + "</g>"


def car(x, duration, bubble=False):
    art = f'''<g transform="translate({x} 25.76) scale(.77)">
      <g>
        <animateTransform attributeName="transform" type="translate" values="-90 0;0 0" dur="{duration}s" calcMode="spline" keySplines=".2 .8 .2 1" fill="freeze"/>
        <g transform="translate(10 82) scale(3)">{pixels(CAR)}</g>
        <text x="21" y="98" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace" font-size="11" font-weight="700" fill="#e2e8f0">&gt;<tspan><animate attributeName="opacity" values="1;1;0;0" dur="1s" repeatCount="indefinite"/>_</tspan></text>'''
    if bubble:
        art += '''<g opacity="0" transform="translate(40 60)">
          <animate attributeName="opacity" values="0;1" begin="1.4s" dur=".3s" fill="freeze"/>
          <path d="M6 16 L12 22 L16 16 Z" fill="#e5e7eb"/>
          <rect width="38" height="18" rx="9" fill="#e5e7eb"/>
          <circle cx="11" cy="9" r="2.4" fill="#6b7280"><animate attributeName="opacity" values="1;.2;1" dur="1.2s" repeatCount="indefinite"/></circle>
          <circle cx="19" cy="9" r="2.4" fill="#6b7280"><animate attributeName="opacity" values="1;.2;1" dur="1.2s" begin=".2s" repeatCount="indefinite"/></circle>
          <circle cx="27" cy="9" r="2.4" fill="#6b7280"><animate attributeName="opacity" values="1;.2;1" dur="1.2s" begin=".4s" repeatCount="indefinite"/></circle>
        </g>'''
    return art + "</g></g>"


cells = []
x = 0
for ch in WORD:
    for row, line in enumerate(GLYPHS[ch.upper()]):
        cells += [(x + col, row) for col, pixel in enumerate(line) if pixel == "#"]
    x += 7 + GAP_CELLS
rows = len(next(iter(GLYPHS.values())))


def wordmark(dx, dy, fill):
    return "\n".join(
        f'<rect x="{X0 + col * PITCH + dx:.1f}" y="{Y0 + row * PITCH + dy:.1f}" width="{PX}" height="{PX}" rx=".7" fill="{fill}"/>'
        for col, row in cells
    )


svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-label="cones: {TAGLINE}">
  <!-- generated by assets/cones.py -->
  <defs>
    <clipPath id="scene-bounds"><rect width="240" height="140"/></clipPath>
    <linearGradient id="ink" gradientUnits="userSpaceOnUse" x1="0" y1="{Y0}" x2="0" y2="{Y0 + rows * PITCH}">
      <stop offset="0" stop-color="#fdba74"/>
      <stop offset=".45" stop-color="#f97316"/>
      <stop offset="1" stop-color="#c2410c"/>
    </linearGradient>
  </defs>
  <g clip-path="url(#scene-bounds)">
    <line x1="0" y1="112" x2="240" y2="112" stroke="#9ca3af" stroke-width="2" opacity=".6"/>
    <line x1="0" y1="124" x2="240" y2="124" stroke="#9ca3af" stroke-width="3" stroke-dasharray="14 10" opacity=".7">
      <animate attributeName="stroke-dashoffset" values="0;-96" dur="1.4s" calcMode="spline" keySplines=".2 .8 .2 1" fill="freeze"/>
    </line>
    {car(-3, 1.8)}
    {car(42, 1.4, bubble=True)}
    {little_feet(224, 4.4)}
    {little_feet(193, 6.7)}
    {little_feet(143, 10, blink=True)}
  </g>
  <g opacity=".35">{wordmark(2.2, 2.4, "#7c2d12")}</g>
  <g>{wordmark(0, 0, "url(#ink)")}</g>
  <text x="{X0}" y="{Y0 + rows * PITCH + 24}" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace" font-size="13" fill="#9ca3af">{TAGLINE}</text>
</svg>
'''
(ASSETS / "cones.svg").write_text(svg)
print(f"assets/cones.svg: {W}x{H}, {len(cells)} wordmark cells")
